### ISSUE TITLE
Wrong parsing version 4.1.1

### ISSUE THREAD

**Issue by benoitbb** [jmrozanec/cron-utils#103]
```
String cron = "* 0/1 * ? * TUE";
CronDefinition cronDefinition = CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ);
CronDescriptor descriptor = CronDescriptor.instance(Locale.UK);
CronParser parser = new CronParser(cronDefinition);
final Cron parse = parser.parse(cron);
final String describe = descriptor.describe(parse);
```

--> output :

> every minute at Wednesday day

Is it a bug ?

Can you have a look please ?

Best regards,

**Comment by jmrozanec** [comment]
@benoitbb Just checked - it is a bug. Thank you for reporting it. If you have some time, you are welcome to contribute a test for it, or even a solution :) Thanks!

**Comment by albuhuba** [comment]
The problem is in the FieldConstraintsBuilder#daysOfWeekMapping. If I change the mapping to be from 0 to 6 this test is working properly, but others are now breaking. Could the problem start from the fact that the java version was changed to 8 and somehow the internal calendar is handling differently the days of the week?  

On the other hand I've seen in the code that there were some other problems with the day-of-week. Can you explain to me what was the problem and what was the solution?

**Comment by jmrozanec** [comment]
@albuhuba almost all computations are based on Jodatime. We abstract internal date representations from those related to crons. The issue is most probably related to a cron specific mapping. For the other DoW issues, please check the corresponding issues and commits. Thanks!

**Comment by jmrozanec** [comment]
@albuhuba Today we updated all Jodatime references to Java8 ZonedDateTime. If working on this issue, please consider updating the branch.

**Comment by lpbak** [comment]
This issue seems to be caused by the fact, that while `com.cronutils.model.definition.CronDefinition` for quartz-like cron expressions is built with a +1 offset in a DAY_OF_WEEK field (call to `withMondayDoWValue(2)` in `com.cronutils.model.definition.CronDefinitionBuilder.quartz()`), this offset is not in any way taken into account by `com.cronutils.descriptor.CronDescriptor`. Unfortunately, fixing this issue (without resorting to some ugly hacks) would probably require some refactoring. Currently, the information about the aforementioned offset seems to be completely lost after `com.cronutils.model.definition.CronDefinition` is built, and hence isn't accessible to the `com.cronutils.descriptor.CronDescriptor`.

**Comment by pangyikhei** [comment]
In 6.0.2 the expression `"* 0/1 * ? * TUE"` does output Tuesday, but doesn't that definition mean every second of every minute?

**Comment by jmrozanec** [comment]
@pangyikhei yes, you are right. The description is not accurate. We should add a test for this case too. Thanks!
