### ISSUE TITLE
How to use the fluent API to add day of week for MON, TUE, WED ?

### ISSUE THREAD

**Issue by mallim** [jmrozanec/cron-utils#104]
Hi

I will like to find out how to use this library's fluent API to construct the day of week to be SUN, TUE instead of 1, 3 for Quartz.

I have looked around and didn't see such FieldExpression available.

Thanks

**Comment by jmrozanec** [comment]
@mallim will take a look tonight at it. If not implemented , will add it soon. Thank you for reaching out!

**Comment by jmrozanec** [comment]
@mallim I took a look at it and committed an implementation. I am not fully convinced by the fact, that you need a factory instance with the same definition as you are passing to the CronBuilder: you cannot detect a mismatch between cron definitions. It also cannot detect if you assign a DoW built field expression to another field, since gets converted before assignment.  If you have a better idea for it, will be welcome. I tried some other approaches, but would not give flexibility to compose FieldExpressions without duplicating some logic of those, and preferred this trade-off.
