### ISSUE TITLE
Drop newly introduced dependency on org.threeten.bp i.e. JSR 310 backport of Java8 date and time API

### ISSUE THREAD

**Issue by meincs** [jmrozanec/cron-utils#175]
Current stable cron-utils 5.0.5 works without the threeten dependency. In a Java8 context this dependency is superfluous and should be avoided. Shouldn't it?

**Comment by jmrozanec** [comment]
@meincs should, but ... 😄  as @curioustechizen pointed out, Android platform supports JDK 1.7 and not [JDK8 yet](https://android-developers.googleblog.com/2017/03/future-of-java-8-language-feature.html) We decided to introduce a temporal dependency on the JSR 130 backport in order to be compatible with Android, and will drop it as soon as JDK8 is supported on Android.  Suggestions on this are welcome!

**Comment by raiscan** [comment]
Hi! Just wondering why this is not exclusive to the android branch, but is present on master? Surely adding dependencies to backport features should be left for branches and older versions, and not added in newer versions of cron-utils? I've had to use 5.0.5 in my project rather than the newest version, as I use JDK8 and do not want extra dependencies.

Thank you for your hard work on the project!

**Comment by curioustechizen** [comment]
@raiscan This is something I discussed with the library maintainers when I contributed the Android backport. I would also like to have a setup where the backport dependencies are not used when building against Java8.

The problem with maintaining separate branches is that it makes it very complicated to pull future enhancements from the main branch into the backport branch. This is because the backport involves quite a bit of adaptation to the code compared to using Java8 out of the box.

I think this is more of a release engineering problem than anything else. Suggestions and contributions are welcome in this regard.

Just to clarify, the problems we face are:
  1. The backports (for example threetenbp) do not have the exact same API as Java8. So, the backport is not a drop-in "polyfill" for the Java8 datetime API.
  2. Several Java8 features (`java.util.functions`, `Optional<T>` etc) are not available as-is on pre-Java8.

The goal we want to achieve is:
  - A single code-base from which we can build 2 separate libraries: One that targets Java8 and one that targets Java7/Android
  - Ability to have the Android branch (if we decide to use separate branches) easily pull in new features and bug fixes from the main branch.

Note that the best way to go forward with this is to restrict the library code itself to use Java7 features going forward. I still have no straightforward answers for the other problems at hand though.

**Comment by meincs** [comment]
Agree with @raiscan. I even would prefer to not stick with Java 7 since Java 9 is already on the way. @raiscan if you hava a look at Guava (i.e. https://github.com/google/guava/wiki/Release21) the better approach seems to be to go on with the latest Java version and provide a backport of the latest changes that don't require Java 8.

**Comment by jmrozanec** [comment]
@meincs @raiscan @curioustechizen we released a new version, porting back to JDK8 and removing guava and org.threeten dependencies!

**Comment by raiscan** [comment]
Great news, thanks for the update!
