### ISSUE TITLE
DoY and Year can be set optional in CronDefinition without failing

### ISSUE THREAD

**Issue by jmrozanec** [jmrozanec/cron-utils#185]
Cron definitions can support just one optional field - the last one - in order to avoid ambiguous representations.

**Comment by jmrozanec** [comment]
@meincs If you have some time, could you look into this issue? Seems the Quartz with DoY defines two optional fields (Y, DoY) but only the last one should be allowed to be optional.

**Comment by meincs** [comment]
This is not a bug this is a feature. The idea is to allow two or even more optional fields, to stay compatible with existing cron definitions and instances of them, i.e. extend the definition but reuse the instances without any modification. This of course means, that preceding optionals have to be set to define a trailing optional.

As I wrote earlier the Cron Builder ensures that mandatory (M) fields can't be defined if a succeeding field has been set optional (O). E.g. it's possible to define M O O but not M O M.

So issue #185 should be closed since this restriction would brake my requirements and isn't necessary.

**Comment by jmrozanec** [comment]
@meincs the arguments provided are good and we can keep this. But there are still some cases where expressions could be ambiguous for custom cron expressions, which we brand and still wish to support. Example: "S M H DoM M DoW DoY" with DoW and DoY both optionals.
We can keep the ability to leave Y and DoY if both defined, optional. But should at the same time enforce a custom expression definition fails if DoW is followed by DoY and both are optional, or some analogous case.
Test cases follow, to provide concrete scenarios. 
Please let us know your thoughts!

**Comment by meincs** [comment]
I guess we have a different understanding of optional.

Given your example ( interchanged DoM and DoW to match with predefined order) 
"S M H DoW M DoM DoY"

I guess you mean "S M H " ( DoW | DoY)

where my interpretation is "S M H DoM M" [ DoW [ DoY ] ]

Thus all custom expression definitions that have been created before can stay as are. But to use the DoY field the DoW field has to be set too.

E.g. 
0 0 0 ? * ? 1/7
0 0 0 1 * ?
0 0 0 1 *

**Comment by jmrozanec** [comment]
@meincs all clear now :smile: Thank you for the clarifications. We are closing the issue and accepting it as a feature. Thanks!
