### ISSUE TITLE
Incorrect Next Execution Time for a number of Unix Cron Expressions

### ISSUE THREAD

**Issue by kensipe** [jmrozanec/cron-utils#228]
Tested on Friday Sept 29, 2017 
0 9 1-7 * 1     1st Mondy of Every Month   -> Sunday (1st of month)
0 9 1-7 * 1-5   1st WeekDay of Every Month -> Sunday (1st of month)
0 9 1-7 * 6-7   1st WeekEnd of Every Month -> Sat (Sept 30 (not the 1st week))
0 9 8-14 * 1-5  2nd WeekDay of Every Month -> Mon (oct 2)
0 9 8-14 * 6-7  2nd WeekEnd of Every Month -> Sat (Sept 30)
0 9 15-21 * 1-5 3rd WeekDay of Every Month -> Mon (Oct 2)
0 9 15-21 * 6-7 3rd WeekEnd of Every Month -> Sat (Sept 30)
0 9 22-28 * 1-5 4th WeekDay of Every Month -> Mon (Oct 2)
0 9 22-28 * 6-7 4th WeekEnd of Every Month -> Sat (Sept 30)

**Comment by pangyikhei** [comment]
The UNIX spec at http://www.unix.com/man-page/linux/5/crontab/ says:

> Note: The day of a command's execution can be specified by two fields -- day of month, and
>        day of week.  If both fields are restricted (i.e., aren't *), the command will be run when
>        **either field** matches the current time.  For example,
>        ``30  4	1,15 * 5'' would cause a command to be run at 4:30 am on the 1st and 15th of each
>        month, plus every Friday. 

Emphasis mine.

> 0 9 1-7 * 1

Translates to 9 AM every month on every Monday and also when the day of month is 1-7.
October 1-7, and 9, 16, 23, 30 of 2017 fits that cron expression (according to the UNIX spec).
If you use `CronType.CRON4J` in your CronDefinition, you'll get your expected next execution time of Oct. 2, 2017, as the CRON4J definition enforces that both Day of Week and Day of Month are matched.
(This was fixed in https://github.com/jmrozanec/cron-utils/issues/203 where the option **matchDayOfWeekAndDayOfMonth** was added to CronDefinitionBuilder and the CRON4J definition has it set to true)

> 0 9 1-7 * 1-5 1st WeekDay of Every Month -> Sunday (1st of month)

9 AM, every month, day of week is Monday to Friday OR day of month is 1-7. October 1 fits that UNIX cron expression. Using the CRON4J definition outputs October 2, 2017 at 9 AM.

> 0 9 1-7 * 6-7 1st WeekEnd of Every Month -> Sat (Sept 30 (not the 1st week))

Your test starts at 2017-09-29T14:46:01.166-07:00. For the same reason as before, Sept. 30 meets the day of week requirement. Note that 6-7 is not valid for the cron4j definition though. You may build a custom cron definition if you wish to permit the use of 7.

> 0 9 8-14 * 1-5 2nd WeekDay of Every Month -> Mon (oct 2)
> 0 9 8-14 * 6-7 2nd WeekEnd of Every Month -> Sat (Sept 30)
> 0 9 15-21 * 1-5 3rd WeekDay of Every Month -> Mon (Oct 2)
> 0 9 15-21 * 6-7 3rd WeekEnd of Every Month -> Sat (Sept 30)
> 0 9 22-28 * 1-5 4th WeekDay of Every Month -> Mon (Oct 2)
> 0 9 22-28 * 6-7 4th WeekEnd of Every Month -> Sat (Sept 30)

These all match the day of week field for the UNIX cron definition.

I suggest building a cron definition like:
```
CronDefinition cronDefinition = CronDefinitionBuilder.defineCron()
        .withMinutes().and()
        .withHours().and()
        .withDayOfMonth().supportsL().and()
        .withMonth().and()
        .withDayOfWeek().withValidRange(0,7).withMondayDoWValue(1).and()
        .enforceStrictRanges()
        .matchDayOfWeekAndDayOfMonth()
        .instance();
```

This passes all of the tests defined in Issue228Test.java

**Comment by jmrozanec** [comment]
@pangyikhei Thank you for the update! Wouldn't you mind sending a PR with the update? We will be glad to merge into master 😄  Thanks!

**Comment by jmrozanec** [comment]
@kensipe fixed! Kudos to @pangyikhei for it!
