### ISSUE TITLE
Cron definition with day of week question mark support incorrectly matches all days of month

### ISSUE THREAD

**Issue by strmer15** [jmrozanec/cron-utils#246]
Failing test:

```
    @Test
    public void testSupportsQuestionMarkDayOfWeekWrongDay() {
        final CronDefinition cronDefinition = CronDefinitionBuilder.defineCron()
                .withSeconds().and()
                .withMinutes().and()
                .withHours().and()
                .withDayOfMonth().supportsQuestionMark().and()
                .withMonth().and()
                .withDayOfWeek().withValidRange(1, 7).supportsQuestionMark().and()
                .instance();

        final CronParser parser = new CronParser(cronDefinition);

        /*
         * Put the asterisk on day of week
         */
        final Cron dayOfMonthCron = parser.parse("* * 0-10 8 10 *");
        ExecutionTime dayOfMonthExecutionTime = ExecutionTime.forCron(dayOfMonthCron);

        ZonedDateTime wrongDay = ZonedDateTime.of(2017, 10, 5, 7, 0, 0,
                0, ZoneId.of("US/Eastern"));

        assertFalse(dayOfMonthExecutionTime.isMatch(wrongDay));

        ZonedDateTime rightDay = ZonedDateTime.of(2017, 10, 8, 7, 0, 0,
                0, ZoneId.of("US/Eastern"));

        assertTrue(dayOfMonthExecutionTime.isMatch(rightDay));

        /*
         * Now put the asterisk on day of month
         */
        final Cron dayOfWeekCron = parser.parse("* * 0-10 * 10 SUN,MON,TUE,WED");
        ExecutionTime executionTime = ExecutionTime.forCron(dayOfWeekCron);

        assertFalse(executionTime.isMatch(wrongDay));

        assertTrue(executionTime.isMatch(rightDay));
    }
```

The problem is that ExecutionTime has two separate methods for generating day candidates - one for question mark support and one for non-question mark support.  In the question mark support generation, the ALWAYS expression is ignored for days of the month and days of the week, which then forces all days of the month and all days of the week to be included as candidates when the field supports question marks in the definition.

**Comment by strmer15** [comment]
Pull Request with fix - https://github.com/jmrozanec/cron-utils/pull/247

**Comment by jmrozanec** [comment]
@strmer15 I am not sure this is an issue. If we take the definition [for '?' as per Quartz](http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/crontrigger.html#special-characters), you use the '?' when the value is defined by another fields that would otherwise define a value for it. If you put an asterisk as value at DoM and a specific value at DoW, the 'always' at DoM will superseed any other value. If putting '?', you know the value to be used, is the one at DoW.
Same holds for other cases. How do you see this? Are we missing something? Thanks!

**Comment by jmrozanec** [comment]
@strmer15 we are rollbacking the changes proposed and closing the issue, since do not match the correct '?' specification. 
'?' specification used at Quartz signals, that we are not defining a concrete value for this field, and the value we consider is defined in another for the same time slice. From Quartz docs: _"useful when you need to specify something in one of the two fields in which the character is allowed, but not the other. For example, if I want my trigger to fire on a particular day of the month (say, the 10th), but don’t care what day of the week that happens to be, I would put '10' in the day-of-month field, and '?' in the day-of-week field."_
Notice that an expression defined as "s m H DoM M DoW" and '?' support should generate the addition of two candidate sets for days: DoM and DoW. At the concrete example of "* * 0-10 8 10 *", this means all days of week and day 8 in October. October 5th is a DoW for 2017, so should be a valid date, not a wrong one as specified in tests. Same goes the other way round: if you specify "* * 0-10 * 10 SUN,MON,TUE,WED", you are selecting all days of month, in which case DoW is always superseeded: any DoM will match the requirement.
If you are willing to use exclusive sets for the given expression, making the asterisk signal that when used for either DoM or DoW, you should define the cron expression without '?' support. In that case should behave as a unix cron.
Please feel free to re-open the issue and continue the conversation.

**Comment by strmer15** [comment]
@jmrozanec I'm not using the Quartz definition - I'm creating a custom one.  I would like to say that the cron definition supports either a '?' or a '*' in the DoM and DoW columns - I know what they both mean, but we generally use them interchangeably in my project.  How would I go about doing that in the current state of this project?

I understand that you don't want the current support for Quartz to suddenly change, so should I add in a special override so that both a '?' and '*' are supported?  i.e. a supportsAsterisk() method that is called after supportsQuestionMark() to enable both?

**Comment by jmrozanec** [comment]
@strmer15 thank you for the clarification! Quartz support should be decoupled of the ability to support '?' and '*': we should be able to support the widest range of scenarios, as long they are possible. We use the Quartz documentation as reference, in order to explain the rationale behind the '?' character. 
We understand that for a custom cron, where you support the '?' character, setting the '*' value to any day related field (DoW, DoM, DoY) should generate all possible day candidates, overriding the rest of the values specified on the day related fields.
We also find that '*' behaves as '?' for cron definitions, where '?' is not supported (ex.: Unix crons). At cron-utils we support this two interpretations. Supporting '?' and '*', with '*' behaving arbitrarily as '?' may cause confusion: would mean support two different behaviors without a different semantic. 
Please help us understand, if there is a scenario we are not able to see, if this explanation helps to clarify the case and if we can provide deeper understanding and further clarifications. Thanks!
