### ISSUE TITLE
Guava dependency is too restrictive

### ISSUE THREAD

**Issue by meincs** [jmrozanec/cron-utils#259]
The declared Guava dependency by the POM is too restrictive. The interval of compatible versions could be opened up to the current version, i.e. 23.4-jre.

Now that the sepcific version is resolved by the org.apache.felix plugin to [18.0,19) and injected into the Jars MANIFEST file, cron-utils is sticked to Guava 18.X in an OSGi environment, although it could use any later release. At least up to 23.4-jre.

Since I'm not sure how to declare the range in maven I'm not going to add a PR. However I guess changing the  POMs Guava version from

`<guava.version>18.0</guava.version>`

to

`<guava.version>[18.0,)</guava.version>`

could do the job.

**Comment by jmrozanec** [comment]
@meincs is a good suggestion. Will implement asap. Thanks!

**Comment by Naxos84** [comment]
Event though I like the idea of version ranges and I also tried this. There are a few things to consider before using this mechanic as stated here https://dev.to/ebud7/maven-version-ranges
The link I provided is just 1 example that I quickly found.

**Comment by jmrozanec** [comment]
@Naxos84 thank you for the information provided. We may run into those issues. We would rather prefer to remove the Guava dependency, but the issue is still valid for the rest of the dependencies.

**Comment by SvenssonWeb** [comment]
How would you like the progression of dependencies to be in the future?
Would working to remove dependencies be a worthwhile goal in itself?
Right now Guava is the only dependency we have exception for commons-cli, which is only used in the CronCLI class.

**Comment by jmrozanec** [comment]
@SvenssonWeb we would prefer to remove dependencies that are not required to provide the functionality we support up to that moment. The goal is that anyone can use cron-utils without having to download many transitive dependencies, which is most important for mobile applications. Another goal is to avoid downloading the same library twice due to version conflicts, as mentioned by meincs.

We should be able to use libraries that help us provide some functionality (ex.: is not desirable to rewrite CLI utilities - it is ok to use commons-cli; if we implement #168, then we must have some dependency on Guava). So the questions are: do we need them and if we need them, how do we depend on them (to maximize version compatibility and avoid transitivities where possible).

**Comment by SvenssonWeb** [comment]
Would it be of interest to develop split is the way Hamcrest has done? 
Moving explicit guava library dependency into a utilities library separate from the core product?
This could in that case also be done with e.g. the CLI parts as well.

**Comment by SvenssonWeb** [comment]
As for the specific question above regarding the specified Guava version, it is not an issue to just specify another guava version in the depending project.

**Comment by jmrozanec** [comment]
@SvenssonWeb it is not an issue to just specify another Guava version in the depending project. 

We could provide split libraries supporting specific parts - that may be a good way to solve this. 

Let's start extracting the CLI part to the [new repo](https://github.com/jmrozanec/cron-utils-cli) and when we implement the #168, then we can release it as a separate library under cron-utils group-id. Thanks! 😄

**Comment by SvenssonWeb** [comment]
It's not really necessary to have a separate repo, you could set up a multi module project in this single repo.
That would keep all releases in sync. And a release would release all parts as a new version.
But it's all a matter of taste I guess :)

**Comment by SvenssonWeb** [comment]
I could set up a pull request with a suggested structure if you want

**Comment by jmrozanec** [comment]
@SvenssonWeb is a possibility, but on the other side, each module will have separate life cycles and thus should also have separate versioning. Since each module will expose an API and we stick to [semantic versioning](http://semver.org/), if a module does not change the public contract or include new features, we should not alter its version. I think this will be the case for this library: the core will get most changes, the satellite libraries will have little variation - at most a dependency change to keep updated, but not on the API side. 
In this schema, I would prefer to keep them in separate repos.

**Comment by SvenssonWeb** [comment]
Okay, sounds good. Keeping them together would keep versioning intact so the same version of both would by definition work together. This will need to be taken into consideration.

**Comment by jmrozanec** [comment]
@SvenssonWeb yes, that is a downside we are aware of and we assume. A way to solve it would be to reference the tag commit hash for a given version at the core as metadata across all satellite libraries. This way we could trace all satellite dependencies to a given core version by knowing the reference hash.

**Comment by SvenssonWeb** [comment]
Good, so... Way forward is to transfer this enhancement to its own repository, and remove Guava from the core system?

**Comment by jmrozanec** [comment]
Yes!

**Comment by SvenssonWeb** [comment]
Nice, I have a pull request ready for the guava removal.

**Comment by jmrozanec** [comment]
@SvenssonWeb thanks!
