### ISSUE TITLE
nextExecution not working as expected

### ISSUE THREAD

**Issue by michaelknigge** [jmrozanec/cron-utils#26]
Hi,

today I've played around with cron-utils but all my efforts to get it working as I expected failed....

I've tried to get a cron expression working that "executes" every monday at 18:00. My efforts to use a custom cron definition failed, so I tried the built-in CRON4J expression....

Here is what I've did:

      // every monday at 18:00
      final String cronExpression = "0 18 * * 1";

      final CronDefinition cronDefinition = CronDefinitionBuilder.instanceDefinitionFor(CronType.CRON4J);
      final CronValidator validator = new CronValidator(cronDefinition);
      System.out.println("isValid:" + validator.isValid(cronExpression));

      final CronParser parser = new CronParser(cronDefinition);
      final Cron cron = parser.parse(cronExpression);

      final ExecutionTime executionTime = ExecutionTime.forCron(cron);

      final CronDescriptor descriptor = CronDescriptor.instance(Locale.UK);
      System.out.println(descriptor.describe(cron));

      final DateTime now = DateTime.now();
      final DateTime nextExec = executionTime.nextExecution(now);
      final DateTime overNextExec = executionTime.nextExecution(nextExec);

      System.out.println("now is: " + now);
      System.out.println("next exec time: " + nextExec);
      System.out.println("over next exec time: " + overNextExec);

This results in

    isValid:true
    at 18:00 at Monday day
    now is: 2015-07-01T17:02:07.556+02:00
    next exec time: 2015-07-01T18:00:00.000+02:00
    over next exec time: 2015-07-01T18:00:00.000+02:00 

As you can see, the date is always the 1st of july, whis is in fact no monday. I also don't understand why the "overnext time" is the same as the "next time".

Anything I did wrong?

Thank you, Michael

**Comment by jmrozanec** [comment]
@michaelknigge Thank you for reporting this. This are two bugs.

Behaviour for days should comply cron definition:
"Commands are executed by cron(8) when the minute, hour, and month of year fields match the current time, and when at least one of the two day fields (day of month, or day of week) matches the current time" [crontab](http://unixhelp.ed.ac.uk/CGI/man-cgi?crontab+5)

Is also a bug how calculation for next execution is performed. overnext time cannot be same as next time. 
Thanks!

**Comment by TriPhoenix** [comment]
I think there might be another issue surrounding this method, I'll put that here (let me know if I should create a separate issue).

This issue is about differences in handling the unix expression "* 0,12 * * *" vs "* */12 * * *" which should both execute to 00:00 and 12:00 every day. In fact the first expression results in an exception after noon:

IllegalArgumentException: The end instant must be greater or equal to the start
  at org.joda.time.base.AbstractInterval.checkInterval(AbstractInterval.java:63)
  at org.joda.time.base.BaseInterval.<init>(BaseInterval.java:94)
  at org.joda.time.Interval.<init>(Interval.java:122)
  at com.cronutils.model.time.ExecutionTime.timeToNextExecution(ExecutionTime.java:172)

This is due to the fact that the candidate list for the first expression only gives [0, 12] as possible hours, while the second one uses [0, 12, 24, 36, 48]. For example evaluating on 2015-07-22 16:46 this gives the prospective next date of 2015-07-22 24:00:00 for the */12 case while the 0,12 case evaluates to 2015-07-22 12:00:00. Latter is in the past and therefore throws an exception in the end.

This also produces erroneous values with patterns like */15. This evaluates to "next day at 6 AM" as soon as you passed 15:00:00 on the current day.

Tested against cron-utils-3.0.0 and cron-utils-2.0.0.

**Comment by jmrozanec** [comment]
@TriPhoenix thank you for reporting this. Will add the corresponding tests and fix as soon as possible.

**Comment by jmrozanec** [comment]
@michaelknigge @TriPhoenix Issue fixed! Thank you for reporting this.

**Comment by jmrozanec** [comment]
@michaelknigge @TriPhoenix [Version 3.1.0](https://github.com/jmrozanec/cron-utils/releases/tag/3.1.0) was released including this fix.

**Comment by devAsterisk** [comment]
**CronType.QUARTZ** has same issue in [3.1.6](https://github.com/jmrozanec/cron-utils/releases/tag/3.1.6).

`at 18:00 at Monday day
now is: 2016-03-18T19:02:51.424+09:00
next exec time: 2016-03-19T18:00:00.000+09:00
over next exec time: 2016-03-20T18:00:00.000+09:00`
