### ISSUE TITLE
Custom cron expressions: trigger just certain days of week in a month

### ISSUE THREAD

**Issue by jmrozanec** [jmrozanec/cron-utils#263]
We would like to express in a cron, that a task should be executed on certain DoW each month. Ex.: all mondays except for the first one. A detailed description is provided in this [Stackoverflow question](https://stackoverflow.com/questions/12950186/java-quartz-cron-expression)

**Comment by SvenssonWeb** [comment]
Unfortunately, because of decisions taken in regards to crontab in unix, DoW and DoM operates independent in the cron format. Specifying both would cause an OR evaluation. "Fixing" this by switching the evaluation to an AND evaluation would give you this feature (e.g * * 8-31 * MON all but first monday in each month). 
But this would work counter to the standard documented version of UNIX Cron. 
Maybe be added as an addition to CronValidation?

**Comment by jmrozanec** [comment]
@SvenssonWeb yes, we understand the requested feature is not aligned with the Unix cron specification. cron-utils aims to provide a complete cron utility, where compliance to a standard would mean at most to limit some features, not to miss them.
Address the issue by adding some CronValidation that would prevent such expressions for UNIX cron definition may be a good idea. We can enforce it from the builder, by specifying if this feature is supported or not, and adding the corresponding validation.

**Comment by SvenssonWeb** [comment]
I'm not arguing against it, I just felt it would be good to highlight that this is not standard.

Should we support ranges as well? e.g `"0 1 0 ? 1/1 MON#2-5 *"`
That would be a logical progression as well, I think.

**Comment by jmrozanec** [comment]
@SvenssonWeb Sure! We are on the same page! We agree with the ranges support you propose: that would make expressions far neater. Thanks! 😄

**Comment by jmrozanec** [comment]
@SvenssonWeb the issue was solved using the multi-cron feature!

**Comment by jmrozanec** [comment]
@SvenssonWeb 7.0.2 is now available!
