### ISSUE TITLE
Remove AndroidTest folder

### ISSUE THREAD

**Issue by SvenssonWeb** [jmrozanec/cron-utils#267]
Is the android test folder contributing to anything, or is it just a duplication of code in the regular test folder?

If it doesn't contribute anything more, we should probably remove it.

**Comment by jmrozanec** [comment]
@SvenssonWeb thank you for pointing this out. The folder was removed!

**Comment by SvenssonWeb** [comment]
Should the manifest file in main be removed as well?

**Comment by jmrozanec** [comment]
@SvenssonWeb not sure. @curioustechizen could you assist us on this?

**Comment by curioustechizen** [comment]
Sorry, I have not been closely following the recent changes in cron-utils so I've not looked into how the Java and Android branches were unified.

The `androidTest` folder was originally introduced because I wanted to have the tests run on an Android device/emulator. The tests in`test` folder run on a desktop JVM. Passing JVM tests do not mean that the tests will pass on Android. The AndroidManifest.xml was also added because it was necessary for `androidTest`.

I'm not sure if there are any Android-specific or Android-sensitive code in cron-utils now. If not, IMO `androidTest` is not needed and hence neither is AndroidManifest.xml

**Comment by jmrozanec** [comment]
@curioustechizen thank you for the response! With release 7.0.0 we moved towards jdk8 since we understand the features we require are fully supported in the latest Android version. For earlier Android versions, cron utils 6.x.y can be used.

**Comment by curioustechizen** [comment]
@jmrozanec ah okay in that case AndroidManifest.xml can be removed too.
