### ISSUE TITLE
Multiple CRON expressions

### ISSUE THREAD

**Issue by mattadamson** [jmrozanec/cron-utils#318]
Team,

Do you know if it's possible to use multiple CRON expressions in a single definition? CRON provides a lot of flexibility within each given time unit however it would be nice to combine them too

Thanks

**Comment by jmrozanec** [comment]
@mattadamson Hi! May we ask you for an example, how you envision this?

**Comment by jmrozanec** [comment]
@mattadamson how about this format:
    "0 0 1 1 *": run every year on January 1st at 12:00AM
    "0 0 2 3 *": run every year on March 2nd at 12:00AM
we merge them into a single expression, pipe-separating cron values from the original definitions:
    "0|0 0|0 1|2 1|3 *|*"
which can be simplified to just the fields that hold different values:
    "0 0 1|2 1|3 *"

**Comment by jmrozanec** [comment]
@mattadamson A first approach was outlined at [multicron branch](https://github.com/jmrozanec/cron-utils/tree/multicron) Your feedback would be valuable for further development.

**Comment by mattadamson** [comment]
Thanks @jmrozanec! Actually the use case I was thinking maybe even be something a custom format could support. Although I'm not clear how you'd create it however your main help page mentions custom formats. 

We'd like to assign a CRON expression to specify a task should be run at arbitary times during the day e.g. 9:00 AM 10:00 AM 11:30 AM 12:00 AM. 

This CRON expression obviously maps to 9:30 ->  0 0,30 9 ? * * *

**Comment by francisdb** [comment]
why not 2 cron extressions with a spearator in between?

**Comment by jmrozanec** [comment]
@francisdb is another possibility. Thanks! My concern would be how can we keep those expressions clear and readable, even if we stack multiple expressions.

**Comment by jmrozanec** [comment]
@mattadamson is not clear to me the case you request. The example you mention should execute always every 30 minutes between 9 and 12? If so, the expression `0 0,30 9-12 ? * * *` would solve it. If we aim for running at arbitrary times in a range, this feature does not comply with standard cron definitions,  but we can introduce a notation, to specify it. Example: `0 0,30 r9-12 ? * * *`: by using an r prefix, would indicate we consider that field for random execution.

**Comment by mattadamson** [comment]
thanks guys. No we would like specific times listed for any given day i.e. 

9:00 AM 10:00 AM 11:30 AM 12:00 AM.

This doesn't fit any pattern of every x minutes as they are irregular intervals. We really want to specify all values in the single expression if possible. The framework also doesn't support multiple expressions however if it can be extended in any form to support this requirement it would be great

**Comment by mattadamson** [comment]
thanks guys. No we would like specific times listed for any given day i.e. 

9:00 AM 10:00 AM 11:30 AM 12:00 AM.

This doesn't fit any pattern of every x minutes as they are irregular intervals. We really want to specify all values in the single expression if possible. The framework also doesn't support multiple expressions however if it can be extended in any form to support this requirement it would be great

**Comment by jmrozanec** [comment]
@mattadamson handling multiple crons in a single expression is possible and its addition would be a great feature. As for building expressions for a specific date, we should build a new specification. Will dig into this and come back with a proposal. Quartz handles the case using a specific builder, decoupled from the cron expressions - perhaps that would be the way to go.

**Comment by jmrozanec** [comment]
@mattadamson @francisdb we implemented the feature! cron-utils supports multi-cron notation, which can be used for the case exposed by @mattadamson achieving irregular patterns by combining multiple crons. The final notation we support is `0 0|0|30|0 9|10|11|12 * * ? *`
The crons can be created by combining multiple crons of same cron definition as well as by parsing a string expression that follows the convention. Feedback is welcome!

**Comment by Naxos84** [comment]
the build fails due to some tests.

https://travis-ci.org/jmrozanec/cron-utils/builds/357684825?utm_source=github_status&utm_medium=notification

Line 1129.

Even though it failed it exited with "0" --> ok.
Is this intended?

**Comment by mattadamson** [comment]
thanks jmrozanec this is indeed perfect for the requirement.  so using 0 0|0|30|0 9|10|11|12 * * ? * could suffice then.  It would be great if we could resolve the test issues causing the build to fail. Do you need any input from me?

Also would this new CRON expression also support the other time portions e.g. if we wanted to restrict to specific days / months?

**Comment by jmrozanec** [comment]
@mattadamson the new expression supports this notation at all cron field levels. As for the build, all tests are passing. Please let us know if you have any issues with that. A new version will be released soon. Best!

**Comment by mattadamson** [comment]
thanks @jmrozanec. I actually tried to run the test provided however it fails

 @Test
 +    public void testParseMulticron(){
 +        String multicron = "0 0|0|30|0 9|10|11|12 * * ? *";
 +        parser = new CronParser(CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ));
 +        Cron cron = parser.parse(multicron);
 +        assertEquals(multicron, cron.asString());
 +    }

java.lang.IllegalArgumentException: Failed to parse '0 0|0|30|0 9|10|11|12 * * ? *'. Invalid chars in expression! Expression: 0|0|30|0 Invalid chars: |||

**Comment by jmrozanec** [comment]
@mattadamson are you importing version 7.0.1 or cloning from master and compiling it locally? Multicron was implemented, but a release was not issued yet with it ...

**Comment by mattadamson** [comment]
I cloned and switched to the multicron branch then did a full build. I then referenced 7.0.2 snapshot from my project.

**Comment by jmrozanec** [comment]
@mattadamson please do not switch to the multicron branch: the correct and full implementation is already in master. Thanks!

**Comment by mattadamson** [comment]
thanks @jmrozanec. This appears to work well on initial tests. It would be great if we could get this in a release soon.

**Comment by jmrozanec** [comment]
Sure! We are finishing a track for improving Cron descriptions, which will alter the original API. If the feature delays more than a week, we will release with current state.

**Comment by mattadamson** [comment]
ok thanks @jmrozanec looking forward to this

**Comment by mattadamson** [comment]
Hi @jmrozanec, do you know when a new release might be happening? Thanks

**Comment by jmrozanec** [comment]
@mattadamson we apologize a new version was not released yet. We got some issues with the release process and we are working on it to fix it as soon as possible. Will keep you updated. Thanks!

**Comment by jmrozanec** [comment]
@mattadamson @francisdb release 7.0.2 is now available! Thank you for contributing to cron-utils!

**Comment by BlakeTNC** [comment]
Hello,
I wanted to give you my perspective on this feature as a "person new to cron", and offer a modification to fix a perceived problem. 
(I'm a professional programmer, but new to using cron formats.)

I read through the discussion leading to this feature, and I saw that you were trying to decide between two formats, quoted here for reference.

"""
Multiple individual crons:
0 0 9 * * ? *
0 0 10 * * ? *
0 30 11 * * ? *
0 0 12 * * ? *

Proposed formats:
0 0 9 * * ? * | 0 0 10 * * ? * | 0 30 11 * * ? * | 0 0 12 * * ? * ("Separated format")
0 0|0|30|0 9|10|11|12 * * ? * ("Squished format")
"""

So, simply put… I find the first Separated format to be super easy for me to read (even being new to cron). The second Squished format is very hard for me to mentally parse, and a bit more difficult to create as well.

I'm guessing that you chose the second format for brevity and maybe popularity. That's still fine. Since people are probably already using it... My suggestion for this (new) feature request is to support both. 

Technical note: There is nothing preventing someone from using both Separated and Squished formats in the same string. So, I'll also added the Squished cron expression from above, to the examples below. 

From a parsing and clarity perspective you can't really support both formats using the same single pipe character. So, you would need a different "entry separation string" for the Separated format. I don't know which characters are already "taken" for normal Cron formats... But off the top of my head a decent separation string might be a double character, to make the cron expressions stand out visually from each other. "||  ##" or maybe square brackets "[]".

Here is what they would each look like:
"0 0 9 * * ? * || 0 0 10 * * ? * || 0 30 11 * * ? * || 0 0 12 * * ? * || 0 0|0|30|0 9|10|11|12 * * ? *"

"0 0 9 * * ? * ## 0 0 10 * * ? * ## 0 30 11 * * ? * ## 0 0 12 * * ? * ## 0 0|0|30|0 9|10|11|12 * * ? *"

"[0 0 9 * * ? *] [0 0 10 * * ? *] [0 30 11 * * ? *] [0 0 12 * * ? *] [0 0|0|30|0 9|10|11|12 * * ? *]"

Personally, I think that maybe the double pipe || looks best. Especially considering that it might be unlikely for one person to utilize both formats in a single string, as I did in these examples. It's also easy enough to remember the syntax... single pipe for squished, double pipe for separated. Without the squished entry, it would look like this:
"0 0 9 * * ? *  ||  0 0 10 * * ? *  ||  0 30 11 * * ? *  ||  0 0 12 * * ? * "

None of these example strings looks amazing, but that's alright by me. They are easier to think about so that's good. 

Unrelated technical note: Is possible for two different cron expressions to result in identical "fire times". For example, one cron expression might say to fire every two hours, and another cron expression might say to fire every three hours. They would both fire at the same time every six hours. I'm guessing that to implement this feature, your code already eliminates the possible duplicate fire times?

Warm regards,
Blake

**Comment by jmrozanec** [comment]
@BlakeTNC thank you for this suggestion. We believe is a good one and just pushed some changes to support this new format as well. Thank you for contributing your thoughts! Best! 😄

**Comment by BlakeTNC** [comment]
You're welcome and thanks for your work. It's great for people to have access to libraries like this. Oh, do you want to reopen this issue? Or I could copy that post to a new issue, if it'll help with the tracking. 
-Blake

**Comment by jmrozanec** [comment]
@BlakeTNC a commit was pushed with this feature implemented 😄 If you would like to create a new issue with this description, we will reference it and close given the implementation is done but will help to track the feature for a new release. Thanks!
