### ISSUE TITLE
The differences between lastExecution & nextExecution

### ISSUE THREAD

**Issue by hokuto-k** [jmrozanec/cron-utils#328]
Hello, I have one question about the subtle difference between `ExecutionTime#lastExecution()` & `nextExecution()`. Not that I'm using version 7.0.1.

## example
If we use the following cron expression with UNIX style:
```
30 * * * *
```
and current time is 19:45, last execution time may be 19:30 (truncated to minutes) and next may be 20:30 as well as last one.

However, the current implementation is not the same as my assumption.

last execution: 19:30:00.YYY (YYY is current milliseconds)
next execution: 20:30 (truncated)

## prediction
Maybe some internal methods whose name are `getPreviousPotentialXXX` return sometimes a result not truncated. Otherwise, `getNextPotentialXXX` methods return always truncated one.

## Question
Is it an intentional result? If not, can I fix it by submitting PR?

**Comment by hokuto-k** [comment]
Actually, I wanted to calculate a gap of both, in the example above, 60 minutes (= 3600 seconds = 3600000 milliseconds).

**Comment by jmrozanec** [comment]
@hokuto-k thanks for reporting this! Actually is not an intentional result: next/previous execution have no milliseconds specification, but I would assume truncating would be the expected result, so that we always get the same output date to a given time - otherwise next/previous wouldn't be comparable for dates differing only at milliseconds level. If you submit a PR we will be glad to merge it! Thanks!

**Comment by hokuto-k** [comment]
@jmrozanec 
Okay, I'll submit some fix for this issue.

**Comment by jmrozanec** [comment]
@hokuto-k thank you for sending the PR - we will be merging soon.

**Comment by jmrozanec** [comment]
@hokkun-dayo release 7.0.2 is now available! Thank you for contributing to cron-utils!
