### ISSUE TITLE
cron mapping not working accurately where '?' symbol is supported.

### ISSUE THREAD

**Issue by zoran119** [jmrozanec/cron-utils#36]
I'm trying to translate a UNIX cron expression to Quartz cron expression. This is how I'm trying to do so (Groovy code):

	Cron unixCron = new CronParser(new CronDefinitionBuilder().instanceDefinitionFor(CronType.UNIX)).parse('* * * * *')
	CronMapper cronMapper = new CronMapper(CronDefinitionBuilder.instanceDefinitionFor(CronType.UNIX), CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ))
	Cron quartzCron = cronMapper.map(unixCron)
	String quartzCronExpression = quartzCron.asString()

However, `* * * * *` gets translated to `0 * * * * * *` which is not valid (I think it should be `0 * * * * * ?`). Is this a bug (or unsupported feature) or is my translation code wrong?

Thanks for your help.

**Comment by jmrozanec** [comment]
@zoran119 The cron-utils translation is good. Consider the following grid:

|cron|seconds|minutes|hours|day of month|month|day of week|year|
-------|-----------|-----------|-------|-----------------|--------|----------------|--------|
|UNIX| - |*|*|*|*|*|-|
|QUARTZ|0|*|*|*|*|*|*|

Since Unix cron definition has no second precision, executing every minute at second zero is an accurate definition. The same goes for the year field: all Unix cron expressions are meant to be executed every year. The correct translation at Quartz would be to use an asterisk for year field.

Do you agree on the approach? Why would you use the question mark at the end?

**Comment by zoran119** [comment]
I think that the translation from UNIX to Quartz is as simple as described in that grid. Attempting to create a Quartz trigger with `0 * * * * * *` gives the following error:

    Support for specifying both a day-of-week AND a day-of-month parameter is not implemented..
    Caused by: java.lang.RuntimeException: CronExpression '0 * * * * * *' is invalid.

**Comment by jmrozanec** [comment]
@zoran119 Yes, you are right, this is a bug. Thank you for reporting it! Will fix it as soon as possible.
You are welcome to contribute either by writing the corresponding tests or submitting a fix.  Thank you!

**Comment by jmrozanec** [comment]
Updating grid, with Quartz compliant expression:

|cron|seconds|minutes|hours|day of month|month|day of week|year|
-------|-----------|-----------|-------|-----------------|--------|----------------|--------|
|UNIX| - |*|*|*|*|*|-|
|QUARTZ|0|*|*|*|*|?|*|
|QUARTZ|0|*|*|?|*|*|*|

**Comment by jmrozanec** [comment]
@zoran119 issue fixed. Thanks for reporting!

**Comment by jmrozanec** [comment]
@zoran119 New version released! Please check details [here](https://github.com/jmrozanec/cron-utils/releases/tag/4.0.0)
