### ISSUE TITLE
Every one hour is creating expression *  , is it possible to generate */1 or 0/1

### ISSUE THREAD

**Issue by sumeetpri** [jmrozanec/cron-utils#374]
```
Cron cron = CronBuilder.cron(CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ))
			    .withYear(always())
			    .withDoM(always())
			    .withMonth(always())
			    .withDoW(questionMark())
			    .withHour(every(1))
			    .withMinute(always())
			    .withSecond(on(0))
			    .instance();
```

The above operation creates 

> 0 * * * * ? *

 , Its correct expression but is it possible to get

>  0 * */1 * * ? *

 or 

> 0 * 0/1 * * ? *

   I was expecting every(1) will create 0/1 or */1.

Is it possible to get 0/1 or */1 if every(1) is an argument passed?

@jmrozanec @palerique

**Comment by jmrozanec** [comment]
@sumeetpri thank you for using cron-utils. Is there a case where we would like to get those expressions even if the three of them are equivalent?

**Comment by sumeetpri** [comment]
I am creating cron expression via API something like . Cron-util creates the cron expression parsing json 
and saves in the database . When the user again view cron details via API it returns always as it saves as *.
For parsing again saved expression i am using . Jon Expression while creating and after saving becomes diffrent json
```
CronParser parser = new CronParser(cronDefinition);
		Cron quartzCron = parser.parse(expression);
```

```
"schedule":{
       "second":{ "value" : 0, "operation":"ON"},
	"minutes":{ "value" : 0, "operation":"ON"},
	"hours":{ "value" : 1 , "operation":"EVERY"},
}			
```

**Comment by jmrozanec** [comment]
@sumeetpri is a good case :smile: let's work on it. Probably can be solved by signaling the case as you exposed or some similar way. Contributions are welcome! :smile: Will try to have a look at it over the weekend. Thanks!

**Comment by sumeetpri** [comment]
class Every of below code needs to be signaled to keep formatting as requested by the user
    
```
@Override
    public String asString() {
        final String expressionAsString = expression.asString();
        if ("*".equals(expressionAsString) && period.getValue() == 1) {
            return expressionAsString;
        }
        return String.format("%s/%s", expressionAsString, period);
    }
```

**Comment by jmrozanec** [comment]
@sumeetpri we have been looking into this and seems we would have to handle many corner cases. We cannot force the model to store information about how was originally represented: that should be responsibility of some visitor with a strategy about how to render that / all fields in a consistent manner. 
What does prevent you storing the original post JSON definition in order to handle it back when requested? Ex.:
 - POST /schedules "{the definition we want to see later}" and returns :id
 - GET /schedules/:id and returns "{the definition we want to see later}"
Could this solve your issue?
