### ISSUE TITLE
Unix crontab

### ISSUE THREAD

**Issue by drieu** [jmrozanec/cron-utils#42]
Hi,
I have the following in my unix crontab :
`00 21 * * * /appli/run.sh`

When I executed 
`ExecutionTime executionTime = ExecutionTime.forCron(parser.parse(cron));`

I have the following error 
`Class
    java.lang.IllegalArgumentException
Message
    Invalid chars in expression! Expression: APPLI Invalid chars: APPLI
`

Does I miss somehting ?

Here is the complete source code : 

       CronDefinition cronDefinition =
            CronDefinitionBuilder.defineCron()
            .withSeconds().and()
            .withMinutes().and()
            .withHours().and()
            .withDayOfMonth()
            .supportsHash().supportsL().supportsW().and()
            .withMonth().and()
            .withDayOfWeek()
            .withIntMapping(7, 0) //we support non-standard non-zero-based numbers!
            .supportsHash().supportsL().supportsW().and()
            .withYear().and()
            .lastFieldOptional()
            .instance();

        //or get a predefined instance
        cronDefinition = CronDefinitionBuilder.instanceDefinitionFor(com.cronutils.model.CronType.QUARTZ);
        //create a parser based on provided definition
        CronParser parser = new CronParser(cronDefinition);
        DateTime now = DateTime.now();
        ExecutionTime executionTime = ExecutionTime.forCron(parser.parse(cron));
        DateTime nextExecution = executionTime.nextExecution(now);

**Comment by jmrozanec** [comment]
@drieu Thank you for using cron-utils!
The error you get is because cron-utils is intended to parse only cron expressions (ex.: "2 7 * * *"), not whole cron entries ("00 21 * * * /appli/run.sh"). 
This decision was made, because there are multiple cron schedulers (unix, java libraries, etc.). All of them share a common pattern to specify cron expressions (with minor variations between some libraries); but have their own way to specify the action to be performed (sometimes as a new column, ex.: [unix cron](http://www.unix.com/man-page/linux/5/crontab/); sometimes somewhere in code, ex.: [quartz](http://quartz-scheduler.org/)).

Using the following entry:

String cron = "00 21 * * *";
ExecutionTime executionTime = ExecutionTime.forCron(parser.parse(cron));

should work ok.

Please let me know if I can provide further help!

**Comment by drieu** [comment]
Thanks for you answer.It works now !
Just for feedback, I'm making a calendar view with unix crontab for a business website.
I used cronutils and fullcalendar and it works well.

**Comment by jmrozanec** [comment]
@drieu You are the first one to report how cron utils is being used inside an app :)  Thank you for your feedback!
