### ISSUE TITLE
Need clarification on time zones

### ISSUE THREAD

**Issue by karstenspang** [jmrozanec/cron-utils#468]
It is not clear to me in which time zone a given cron string is interpreted.
I assume that there is no time zone associated with the cron string itself, but when calling e.g. `ExecutionTime.nextExecution(ZonedDateTime)`, the time zone of the parameter is used to interpret the cron string.
Is this correct? Please clarify this in the documentation, for example in the javadoc for `ExecutionTime`.
Thanks

**Comment by jmrozanec** [comment]
@karstenspang the cron string is always interpreted in the local time of the machine, where is executed. We provide the ZonedDateTime, so that you have some more flexibility: you are no longer constrained to your local timezone. If you have some time, we would appreciate a PR with the requested documentation. We will review it and merge ASAP. Thanks! 😄

**Comment by jmrozanec** [comment]
@karstenspang we updated the Javadoc. Best!

**Comment by karstenspang** [comment]
Thanks

But then I will consider this as an enhancement request, i.e. make it possible to define the time zone in which the cron string is interpreted.

Looking at the code, I think it is beyond me to figure out how to do that, so I can't contribute this.

**Comment by jmrozanec** [comment]
@karstenspang you are always welcome to suggest new features. As per the original definition, [considering timezones is not a feature](https://man7.org/linux/man-pages/man5/crontab.5.html). But at cron-utils we make an effort to stretch the existing cron limitations, and may implement the request in the future 😄 Thanks!
