### ISSUE TITLE
Wrong description for * */2 * * *

### ISSUE THREAD

**Issue by arunvelsriram** [jmrozanec/cron-utils#477]
For `* */2 * * *` the expected description should be something like "every minute of every second hour". But actual description that we are getting is "every 2 hours".

Sorry if this a know bug already. I searched the issues but can't find anything related.

**Comment by jmrozanec** [comment]
@arunvelsriram thank you for reporting this. May we ask you to send a PR with a test? Thanks! 😄

**Comment by mccartney** [comment]
When looking into it, I think the problem is with default handling of `Always` values. So for an expression like `* */2 * * *` the handling of more specific values (left of `*/2`) and less specific values (right of `*/2`) is the same. Namely empty String. While it should be different.

I am not fully sure, but I think it should be:
- ignore all `*` from the right, they result in empty String,
- all the rest should be handled and result in non-empty String.
