### ISSUE TITLE
generate a cron exps

### ISSUE THREAD

**Issue by Jacob201311** [jmrozanec/cron-utils#82]
I find CronBuilder in the project, but I think there is less function for this Class, when will you complete it?
For now, I just want to generate a expression. for example, I fill 1,2,3,4 in day of month, it should be generated to 1-4
It is difficult to generate a cron use new Cron(cronDefinition, fields)

**Comment by jmrozanec** [comment]
@Jakob201311 CronBuilder is not complete. I left it halfway, since is also an opportunity to rethink how are some components designed in the library, and I have no time to do a major refactor right now. You are welcome to contribute on it, so that we get it done.

**Comment by jmrozanec** [comment]
Related to #48

**Comment by jmrozanec** [comment]
@Jacob201311 Reviewing the issue, I was doubting if it was better to have validations when creating an instance of any field value or it would be better to just assign values to the fields, and validate a posteriori considering any cron definition. The approach has immediate consequences on how we parse, build and validate.
The way is done now, it gives immediate feedback if some values are not correct; but may create too many constraints if you just want to build a cron expression. By decoupling validation from representation, we may also gain flexibility on how we perform validations on multiple fields (ex.: Quartz does not support values on DoM and DoW fields at the same time: one of both must be a question mark.

Perhaps the best path to follow would be to branch master and try a prototype on another branch in order to better understand pros/cons. You are most welcome to help on this task.

**Comment by Jacob201311** [comment]
@jmrozanec sorry for replying so late. so far, I am very busy with my work. so, I have no time for the task. sorry about that.

**Comment by jmrozanec** [comment]
@Jacob201311 no problem! We all have a job to attend first. I have done the refactor mentioned above, and now it should be easier to create a cron expression. Will release a new version including those changes soon.

**Comment by jmrozanec** [comment]
@Jacob201311 Now we have a [CronBuilder](https://github.com/jmrozanec/cron-utils/blob/3ab9f8f5bb6c928c39130df15abb5c5c04aa9349/src/main/java/com/cronutils/builder/CronBuilder.java)! Will be released soon with version 4.0.0, after we fix some more issues.

An example is available at the [README.md](https://github.com/jmrozanec/cron-utils) file.

**Comment by jmrozanec** [comment]
@Jacob201311 New version released! Please check details [here](https://github.com/jmrozanec/cron-utils/releases/tag/4.0.0)
